# Generated by Django 5.0.8 on 2024-08-12 13:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('expiration_date', models.DateField(editable=False)),
                ('cvv', models.CharField(editable=False, max_length=3)),
                ('card_type', models.CharField(choices=[('VISA', 'visa'), ('MASTERCARD', 'Mastercard'), ('DISCOVER', 'discover'), ('AMEX', 'amex')], max_length=20)),
                ('account_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('SAVINGS', 'Savings'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
