# Generated by Django 5.0.8 on 2024-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banker_name', models.CharField(choices=[('Jonathan Davies', 'Jonathan Davies'), ('Samantha Brooke', 'Samantha Brooke'), ('David Smith', 'David Smith'), ('Jim White', 'Jim White'), ('Simon Jordan', 'Simon Jordan')], max_length=50)),
                ('reason_for_booking', models.TextField(max_length=500)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
